name: Build & Release

on:
  push:
    branches:
      - main  # runs whenever you push to main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean & Build
        run: ./gradlew clean build

      - name: Get Version
        id: version
        run: |
          VERSION="1.0.$GITHUB_RUN_NUMBER"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: "Release v${{ steps.version.outputs.version }}"
          body: |
            🚀 Auto-generated release for version v${{ steps.version.outputs.version }}
            - Clean & build passed ✅
            - Ready for JitPack publishing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
